# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsweather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='wind_direction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='abs_humidity',
            field=models.FloatField(null=True, verbose_name='absolute humidity'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='atmo_opacity',
            field=models.CharField(max_length=100, null=True, verbose_name='atmospheric conditions'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ls',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.FloatField(null=True, verbose_name='high temp in Centigrade'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp_fahrenheit',
            field=models.FloatField(null=True, verbose_name='high temp in Fahrenheit'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.FloatField(null=True, verbose_name='low temp in Centigrade'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp_fahrenheit',
            field=models.FloatField(null=True, verbose_name='low temp in Fahrenheit'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pressure descriptor'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunrise',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunset',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
    ]
